name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: neverendingqs/gh-action-node-update-deps@bd9bf7e5c45ac5a270cc15d9ff7b0eedb0678701
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        git-user-name: haha
