name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: neverendingqs/gh-action-node-update-deps@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bump-version: patch
          git-user-name: haha
          git-user-email: haha@example.com
          package-manager: yarn
