on:
  issue_comment:
    types: [created]

jobs:
  terminal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - id: terminal
        uses: neverendingqs/gh-action-terminal@main
        with:
          command-prefix: /term
      - run: |
          echo "exit code: ${{ steps.terminal.outputs.exit-code }}"
          echo "stdout: ${{ steps.terminal.outputs.stdout }}"
