name: gh-action-node-update-deps

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: neverendingqs/gh-action-node-update-deps@main
      with:
        bump-version: patch
        commit-message-prefix: fix
        package-manager: yarn
        target-version: patch
        pre-commit-script: rm package-lock.json
