on:
  issue_comment:
    types: [created]

jobs:
  run-and-update:
    if: contains(github.event.comment.html_url, '/pull/')
    runs-on: ubuntu-latest
    steps: 
      - id: acknowledge
        uses: actions/github-script@v3
        with:
          script: |
            github.reactions.createForIssueComment({
              comment_id: context.payload.comment.id,
              owner: context.repo.owner,
              repo: context.repo.repo,
              content: '+1',
            });
      - id: get-ref
        uses: actions/github-script@v3
        with:
          result-encoding: string
          script: |
            const response = github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.comment.id
            });
            
            console.log(JSON.stringify(response, null, 2));
            const { head: { ref } } = response;
            
            return ref;
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.get-ref.outputs.result }}
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - id: terminal
        uses: neverendingqs/gh-action-terminal@main
      - run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          
          git commit -am "chore: update after ${COMMAND}."
          git push
        env:
          COMMAND: ${{ steps.terminal.outputs.command }}
          
