name: gh-action-node-update-deps

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: neverendingqs/gh-action-node-update-deps@249f8bcec25e5b98564db41b182c1b1053681189
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        bump-version: patch
        pr-labels: test
