on:
  issue_comment:
    types: [created]

jobs:
  terminal:
    if: contains(github.event.comment.html_url, '/pull/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - id: terminal
        uses: neverendingqs/gh-action-terminal@main
      - run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          
          git commit -am "chore: update after ${COMMAND}."
          git push
        env:
          COMMAND: ${{ steps.terminal.outputs.command }}
          
