name: Release Branch Check

on:
  pull_request:
  
jobs:
  check-pr-base:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: If base branch is 'main', check if pull request branch is 'release/*'
        # if: ${{ github.event.pull_request.base.ref == 'main' }}
        run: |
          if [[ ! "$HEAD_BRANCH" =~ ^release/+ ]]; then
            echo "Invalid branch name '${HEAD_BRANCH}'. Only branches prefixed with 'release/' can be merged to 'main'."
            exit -1
          fi
        env:
          HEAD_BRANCH: ${{ github.event.pull_request.base.ref }}
    
